# Generated by Django 6.0 on 2025-12-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code_data',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='qr_code_image',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
