# Generated by Django 6.0 on 2026-01-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_qr_code_data_booking_qr_code_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
